Add style and behaviour
MedouneSGB/Waxtane pull request #22
Opened 2022-06-15 21:51 UTC by honorableCon

- Change placeholder based on selected langue
- Add animation on hover on language's select buttons

2022-06-15 22:47 UTC, dofbi requested changes

2022-06-15 22:47 UTC, dofbi commented on web/src/styles/home.css
> +	transform: scale(1.2);
Hello @honorableCon 
great job pourquoi pas improve avec une animation avec l'attribut transition pour rendre cela soft.
Comme c'est trop brusque

2022-06-16 20:47 UTC, honorableCon commented on web/src/styles/home.css
> +	transform: scale(1.2);
Oui, c'est vrai.. :100: 

Transition done ! :)

2022-06-17 12:35 UTC, MedouneSGB approved these changes
Great updates @honorableCon ✨🚀

2022-06-17 20:15 UTC, merged